### ISSUE TITLE
inpropper printing to the screen in driver-loop

### ISSUE THREAD

**Issue by minimum-sauce** [parapluu/mce-typed#1]
When running the program, the history that is displayed from the 'user_read' function gets displayed as raw input with the '\n' still present: 
"--- session start ---\nM-evaluate input:\nfunction factorial(n) {\n    return n < 2 \n           ? n \n           : n * factorial(n - 1);\n}\nfactorial(5);\nM-evaluate value:\n120"

instead of the more readable output:

--- session start ---
    M-evaluate input:
    function factorial(n) {
        return n < 2
               ? n
               : n * factorial(n - 1);
    }
    factorial(5);
    M-evaluate value:
    120 ""

Although this does not fully fix the inpropper printing, one solution is to change in the user_read function to run:
display("", prompt_string); 
instead of: 
display(prompt_string);
There is still ' "" ' being printed but I haven't found a way to remove that. 
If there is a way to remove that as well or an alternative solution is found, please get back to this issue.

**Comment by sashabjorkman** [comment]
Hi. Using `console.log` instead will probably do just fine. Warmest regards

**Comment by johannesborgstrom** [comment]
Fixed, thanks.
