### ISSUE TITLE
BUG: if (test) {consequent} else {alternate} is not recognised as a conditional expression.

### ISSUE THREAD

**Issue by hato1883** [parapluu/mce-typed#11]
Evaluating something like:
```
if (true) { 1; } else { 0; }
```
Results in:
```
unknown syntax -- evaluate [ "conditional_statement",
[ ["literal", [true, null]],
[["literal", [1, null]], [["literal", [0, null]], null]]]]
```
Because it is tagged as a `conditional_statement` instead of a `conditional_expression` which the `is_conditional()` function is searching for at line (115).

Talking about branch homework11.

**Comment by malyzajko** [comment]
Indeed, the branch does not support conditional statements, only conditional expressions with the `a ? b : c` syntax (for simplicity, not because it would be hard to implement).

**Comment by hato1883** [comment]
so its intended feature of the branch?
Then i'll mark it as closed :)

**Comment by malyzajko** [comment]
Yeah, it is a current "feature" (we may fix/change this in the future).
